### ISSUE TITLE
Understanding integration of ffw in Honggfuzz

### ISSUE THREAD

**Issue by prashast** [dobin/ffw#30]
Hi, I noticed that the socketfuzzer patch in Honggfuzz has been provided by you and would be obliged if I could get some details regarding its integration into Honggfuzz from you.

In the case of this socketfuzzer paradigm, hongfuzz attaches to a long standing fuzz target
(server), exposes a socket for the external fuzzer to connect and then orchestrates the
fuzzing process.

One thing that I am not able to grasp is how is the hongfuzz instance aware of the bitmap
that is being updated for an already running server. As far as I understand from the code, the bitmap is
kept in-memory and updated when the registered callbacks are triggered and didn't see it being written to disk.

Also, I've been having trouble dumping the coverage files using the `covdir_all` option when I try to use it in conjunction with the socketfuzzer functionality. Is it a configuration issue on my end or should I triage this issue further?

**Comment by dobin** [comment]
I dont know much about how Honggfuzz works internally with the bitmaps (as it supports like 5 different methods). But it already has long-running server fuzzing support, including updating bitmaps.

The integration into honggfuzz is messy, its mostly patching around in fuzz.c and arch.c. 

Maybe for some reasen i disabled writing the coverage information to disk, via https://github.com/google/honggfuzz/blob/master/fuzz.c#L124 ?
