### ISSUE TITLE
minimize error

### ISSUE THREAD

**Issue by y1026** [dobin/ffw#9]
Hello,

I succeeded in the tutorial.

There are conflict files in out.

but, I get an error when I execute the minimize command.

Thanks

```
y1026@y1026:~/ffw/vulnserver$ ./fuzzing.py --minimize --debug
Client Manager
Network Server Manager
Processing 24 outcome files
Traceback (most recent call last):
  File "./fuzzing.py", line 102, in <module>
    sys.exit(main())
  File "./fuzzing.py", line 98, in main
    framework.realMain(config)
  File "/home/y1026/ffw/vulnserver/../framework.py", line 189, in realMain
    mini.minimizeOutDir()
  File "/home/y1026/ffw/vulnserver/../verifier/minimizer.py", line 42, in minimizeOutDir
    idx = crashDetails["faultOffset"]
KeyError: 'faultOffset'
```

**Comment by dobin** [comment]
Seems it could not detect the RIP of the instruction which produced the crash. I'll do a patch.

**Comment by y1026** [comment]
@dobin 

Hello,

Thank you for your reply.

ffw is very good tool.

And, tutorial-honggmode.md It seems you need to modify the document.

https://github.com/dobin/honggfuzz can not use --socket_fuzzer.

Thanks.

**Comment by dobin** [comment]
Indeed, the tutorial was written with my private honggfuzz patch in mind. It got accepted, and we can use the official google honggfuzz.

**Comment by dobin** [comment]
i think if there is no faultOffset (EIP where error occured), minimizer is pretty useless. I only fixed the python error. Would need more information to reproduce it.
